import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import localFont from "@next/font/local";

const poppins = localFont({
  src: [
    {
      path: '../../public/fonts/anta-regular.ttf',
      weight: '400'
    },
  ],
  variable: '--font-poppins'
})

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Lugar real estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} font-sans`}>
      <body
      className={`${fontSans.variable} font-sans min-h-screen bg-background antialiased`}
        // className={cn(
        //   "min-h-screen bg-background antialiased",
        //   fontSans.variable
        // )}
      >
        {children}
      </body>
    </html>
  );
}
