import type { Metadata } from "next";
import "./globals.css";
import localFont from "@next/font/local";

const poppins = localFont({
  src: [
    {
      path: '../../public/fonts/anta-regular.ttf',
      weight: '400'
    },
  ],
  variable: '--font-poppins'
})


export const metadata: Metadata = {
  title: "Lugar real estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} font-sans`}>
      <body
      className=' min-h-screen bg-background antialiased'
      >
        {children}
      </body>
    </html>
  );
}
